# Generated by Django 6.0.2 on 2026-02-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_staff_user_staff_password_staff_username'),
        ('tickets', '0005_rename_action_ticketactivity_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.issuecategory'),
        ),
    ]
