# Generated by Django 6.0.2 on 2026-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('org_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('AMC', 'AMC'), ('NON_AMC', 'NON AMC'), ('HAND_HOLDING', 'Hand Holding'), ('OTHER', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
