# Generated by Django 6.0.2 on 2026-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='message',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='staff',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
