# Generated by Django 6.0.2 on 2026-02-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_message_ticketcomment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketactivity',
            old_name='action',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.issuecategory'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('WORKING', 'Working'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.subissue'),
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
